name: Github Actions PyTests Pipeline
run-name: ${{ github.actor }} is running the tests.
on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install pytest selenium

#      - name: Install Chrome Driver
#        uses: nanasess/setup-chromedriver@v2
#        with:
#          chromedriver-version: '113.0.5672.63'
#
#      - name: Run Chrome Driver
#        run: |
#           export DISPLAY=:99
#           chromedriver --url-base=/wd/hub &
#           sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

      - name: Set up Chrome driver
        run: |
          CHROME_VERSION=$(google-chrome-stable --version | grep -oP '(?<=Google Chrome )[^ ]+')
          CHROME_DRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}")
          curl -s -o chromedriver_linux64.zip "https://chromedriver.storage.googleapis.com/${CHROME_DRIVER_VERSION}/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip -d $HOME
          echo "export PATH=\$HOME:\$PATH" >> $GITHUB_ENV

      - name: Run Tests
        run: pytest
#      - uses: pavelzw/pytest-action@v2
#        with:
#          emoji: false
#          verbose: false
#          job-summary: true
